import Head from 'next/head'
import Image from 'next/image'
import MainLayout from '@/components/MainLayout'
import Link from 'next/link'

// Import the FontAwesomeIcon component
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// import the icons you need
import {
    faArrowDown,
    faeject

} from "@fortawesome/free-solid-svg-icons";


// import Pages
import Landing from "./components_Home/0Landing"
import AboutUS from "./components_Home/1AboutUS"
import Member from "./components_Home/2Member";
import Project from "./components_Home/3Project";
import Join from "./components_Home/4Join";
// import Pages

export default function Home() {
    return (
        <>
            <Head>
                <title>Developer portal</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/myAmges.svg" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@500;600;700;800&display=swap" rel="stylesheet"></link>

            </Head>

            <MainLayout>
                <Landing />

                <AboutUS />

                <Member />

                <Project />

                <Join />
            </MainLayout>
        </>
    )
}
